package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Sandbox_jsp extends org.apache.jasper.runtime.HttpJspBase implements org.apache.jasper.runtime.JspSourceDependent {

    private static java.util.Vector _jspx_dependants;

    private org.apache.jasper.runtime.ResourceInjector _jspx_resourceInjector;

    public Object getDependants() {
        return _jspx_dependants;
    }

    public void _jspService(HttpServletRequest request, HttpServletResponse response) throws java.io.IOException, ServletException {
        JspFactory _jspxFactory = null;
        PageContext pageContext = null;
        HttpSession session = null;
        ServletContext application = null;
        ServletConfig config = null;
        JspWriter out = null;
        Object page = this;
        JspWriter _jspx_out = null;
        PageContext _jspx_page_context = null;
        try {
            _jspxFactory = JspFactory.getDefaultFactory();
            response.setContentType("text/html");
            pageContext = _jspxFactory.getPageContext(this, request, response, null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;
            String resourceInjectorClassName = config.getInitParameter("com.sun.appserv.jsp.resource.injector");
            if (resourceInjectorClassName != null) {
                _jspx_resourceInjector = (org.apache.jasper.runtime.ResourceInjector) Class.forName(resourceInjectorClassName).newInstance();
                _jspx_resourceInjector.setContext(application);
            }
            out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
            out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n");
            out.write("    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
            out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n");
            out.write("  <head>\n");
            out.write("    <title>\n");
            out.write("                  XWiki - Sandbox - WebHome\n");
            out.write("              </title>\n");
            out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
            out.write("    <meta http-equiv=\"imagetoolbar\" content=\"no\"/>\n");
            out.write("    <meta name=\"revisit-after\" content=\"7 days\" />\r\n");
            out.write("<meta name=\"description\" content=\"XWiki for sharing information\" />\r\n");
            out.write("<meta name=\"keywords\" content=\"wiki\" />\r\n");
            out.write("<meta name=\"distribution\" content=\"GLOBAL\" />\r\n");
            out.write("<meta name=\"rating\" content=\"General\" />\r\n");
            out.write("<meta name=\"author\" content=\"\" />\r\n");
            out.write("<meta http-equiv=\"reply-to\" content=\"\" />\r\n");
            out.write("<meta name=\"language\" content=\"en\" />\r\n");
            out.write("<link rel=\"alternate\" type=\"application/rss+xml\" title=\"Wiki Feed RSS\" href=\"/xwiki/bin/view/Main/WebRss?xpage=rdf\" />\r\n");
            out.write("<link rel=\"alternate\" type=\"application/rss+xml\" title=\"Blog RSS Feed\" href=\"/xwiki/bin/view/Main/BlogRss?xpage=rdf\" />\n");
            out.write("    <link href=\"/xwiki/bin/skin/skins/toucan/style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
            out.write("        <link href=\"/xwiki/yui/treeview/assets/tree.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
            out.write("<link href=\"/xwiki/bin/skin/skins/albatross/css/lightbox/lightbox.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
            out.write("<!--[if IE]>\n");
            out.write("  <link href=\"/xwiki/bin/skin/skins/albatross/css/lightbox/lightboxIE.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
            out.write("<![endif]-->\n");
            out.write("\n");
            out.write("\n");
            out.write("    \n");
            out.write("\n");
            out.write("    <script type=\"text/javascript\" src=\"/xwiki/skins/albatross/skin.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/prototype.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/skins/albatross/scriptaculous/scriptaculous.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/skins/albatross/accordion/accordion.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/skins/albatross/xwiki.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/skins/albatross/browserdetect.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/skins/albatross/chwScripts.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/bin/skin/skins/albatross/scripts/table/tablefilterNsort.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/bin/skin/skins/albatross/fullscreenEdit.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/bin/skin/skins/albatross/usersandgroups.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/skins/albatross/suggest/ajaxSuggest.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/bin/skin/skins/albatross/scripts/lightbox/lightbox.js\"></script>\n");
            out.write("<script type=\"text/javascript\" src=\"/xwiki/bin/skin/skins/albatross/scripts/shortcuts.js\"></script>\n");
            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write("  </head>\n");
            out.write("      <body id=\"body\" class=\"xwiki viewbody hideleft\">\n");
            out.write("  <!-- These elements will be closed in the footer vm file -->\n");
            out.write("<div id=\"xwikimaincontainer\">\n");
            out.write("<div id=\"xwikimaincontainerinner\">\n");
            out.write("\n");
            out.write(" <div id=\"headerglobal\" class=\"layoutsection\">\n");
            out.write("<div class=\"minwidthb\"></div>\n");
            out.write("  <div id=\"company\">\n");
            out.write("  <div id=\"companylogo\">\n");
            out.write("    <a href=\"/xwiki/bin/view/Main/\" title=\"Home\" rel=\"home\">\n");
            out.write("      <img src=\"/xwiki/skins/toucan/logo.png\" alt=\"XWiki\" width=\"200\" height=\"70\"/>\n");
            out.write("    </a>\n");
            out.write("  </div>\n");
            out.write("  <div id=\"globaldoctitle\">\n");
            out.write("    <h1><a href='/xwiki/bin/view/Sandbox/'>Training Zone</a></h1>\n");
            out.write("  </div>\n");
            out.write("  </div>\n");
            out.write("  <div id=\"globallinks\">\n");
            out.write("    <div id=\"globalmenu\">\n");
            out.write("      <a class=\"glink\" href=\"/xwiki/bin/view/XWiki/dieisii\" id=\"headeruser\">Dace StrÄlniece</a> <span class=\"separator\"> | </span>\n");
            out.write("      <a class=\"glink\" href=\"/xwiki/bin/logout/XWiki/XWikiLogout?xredirect=http%3A%2F%2F172.16.6.129%3A8180%2Fxwiki%2Fbin%2Fview%2FSandbox%2F\" id=\"headerlogout\">Log-out</a><span class=\"separator\"> | </span>\n");
            out.write("      <a class=\"glink\" href=\"/xwiki/bin/admin/XWiki/XWikiPreferences\" id=\"headeradmin\">Administration</a> <span class=\"separator\"> | </span>\n");
            out.write("    </div> \n");
            out.write("  </div>\n");
            out.write("</div>\n");
            out.write("\n");
            out.write(" <div id=\"headerspace\" class=\"layoutsection\">\n");
            out.write("<div class=\"minwidth\"></div>\n");
            out.write("<hr/>\n");
            out.write("  <div id=\"breadcrumbs\">\n");
            out.write("    <span class=\"breadcrumbspace\"><a href=\"/xwiki/bin/view/Sandbox/\">Sandbox</a>: </span>\n");
            out.write("<a href='/xwiki/bin/view/Main/'>Welcome to your wiki</a> &gt; <a href='/xwiki/bin/view/Sandbox/'>Training Zone</a>\n");
            out.write("  </div>\n");
            out.write("<hr/>\n");
            out.write("</div>\n");
            out.write("\n");
            out.write("\n");
            out.write("<div id=\"menuview\"> \n");
            out.write("  <div id=\"actionmenu\" class=\"layoutsubsection\">\n");
            out.write("<h3 id=\"xwikimenutitle\" class=\"hidden\">Top Menu</h3>\n");
            out.write("<div class=\"rightmenu\"><a id=\"tmDoc\" href='http://www.xwiki.org/xwiki/bin/view/Main/Documentation' onclick=\"openURL('http://www.xwiki.org/xwiki/bin/view/Main/Documentation', '_blank'); return false;\"><strong>Documentation</strong></a></div>\n");
            out.write("<div class=\"leftmenu\">\n");
            out.write("<div class=\"topmenuentry\" onmouseover=\"showsubmenu(this);\" onmouseout=\"hidesubmenu(this);\" id=\"tmEdit\">\n");
            out.write("<a class=\"tme\"  href=\"/xwiki/bin/edit/Sandbox/WebHome\" ><strong>Edit</strong></a><span class=\"hidden menucolon\">: </span><span class=\"submenu hidden\">\n");
            out.write("<a style=\"display:none;\" href=\"/xwiki/bin/edit/Sandbox/WebHome\" accesskey=\"e\">edit</a>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/edit/Sandbox/WebHome?&amp;editor=wiki\">Wiki</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/edit/Sandbox/WebHome?&amp;editor=wysiwyg\">WYSIWYG</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/inline/Sandbox/WebHome\">Inline form</a></span>\n");
            out.write("<span class=\"submenuseparator\">&nbsp;</span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/edit/Sandbox/WebHome?editor=rights\">Page access rights</a></span>\n");
            out.write("<span class=\"submenuseparator\">&nbsp;</span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/edit/Sandbox/WebHome?editor=object\">Objects</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/edit/Sandbox/WebHome?editor=class\">Class</a></span>\n");
            out.write("</span></div>\n");
            out.write("<script type=\"text/javascript\">\n");
            out.write("//<![CDATA[\n");
            out.write("  shortcut.add(\"e\",function() { location.href=\"/xwiki/bin/edit/Sandbox/WebHome\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"k\",function() { location.href=\"/xwiki/bin/edit/Sandbox/WebHome?&editor=wiki\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"g\",function() { location.href=\"/xwiki/bin/edit/Sandbox/WebHome?&editor=wysiwyg\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"f\",function() { location.href=\"/xwiki/bin/inline/Sandbox/WebHome\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"r\",function() { location.href=\"/xwiki/bin/edit/Sandbox/WebHome?editor=rights\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"o\",function() { location.href=\"/xwiki/bin/edit/Sandbox/WebHome?editor=object\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"s\",function() { location.href=\"/xwiki/bin/edit/Sandbox/WebHome?editor=class\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("//]]>\n");
            out.write("</script>\n");
            out.write("<div class=\"topmenuentry\" onmouseover=\"showsubmenu(this);\" onmouseout=\"hidesubmenu(this);\" id=\"tmShow\">\n");
            out.write("<a class=\"tme\"  href=\"/xwiki/bin/view/Sandbox/?viewer=code&amp;\" ><strong>Show</strong></a><span class=\"hidden menucolon\">: </span><span class=\"submenu hidden\">\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/view/Sandbox/?viewer=comments&amp;\">Comments</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/view/Sandbox/?viewer=attachments&amp;\">Attachments</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/view/Sandbox/?viewer=history&amp;\">History</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/view/Sandbox/?viewer=code&amp;\">Wiki code</a></span>\n");
            out.write("</span></div>\n");
            out.write("<script type=\"text/javascript\">\n");
            out.write("//<![CDATA[\n");
            out.write("  shortcut.add(\"c\",function() { location.href=\"/xwiki/bin/view/Sandbox/?viewer=comments&\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"a\",function() { location.href=\"/xwiki/bin/view/Sandbox/?viewer=attachments&\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"h\",function() { location.href=\"/xwiki/bin/view/Sandbox/?viewer=history&\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("    shortcut.add(\"d\",function() { location.href=\"/xwiki/bin/view/Sandbox/?viewer=code&\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  //]]>\n");
            out.write("</script>\n");
            out.write(" <div class=\"topmenuentry\" onmouseover=\"showsubmenu(this);\" onmouseout=\"hidesubmenu(this);\" id=\"tmPrint\">\n");
            out.write("<a class=\"tme\"  href=\"javascript:window.print()\" ><strong>Print</strong></a><span class=\"hidden menucolon\">: </span><span class=\"submenu hidden\">\n");
            out.write("<span class=\"submenuitem\"><a href=\"javascript:window.print()\">Print</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/view/Sandbox/?xpage=print&amp;\">Print preview</a></span>\n");
            out.write("<span class=\"submenuseparator\">&nbsp;</span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/export/Sandbox/WebHome?format=pdf&amp;\">Export as PDF</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/export/Sandbox/WebHome?format=rtf&amp;\">Export as RTF</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/export/Sandbox/WebHome?format=html&amp;\">Export as HTML</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/export/Sandbox/WebHome?format=xar&amp;name=Sandbox.WebHome&amp;pages=Sandbox.WebHome&amp;\">Export as XAR</a></span>\n");
            out.write("</span></div>\n");
            out.write("<div class=\"topmenuentry\" onmouseover=\"showsubmenu(this);\" onmouseout=\"hidesubmenu(this);\" id=\"tmFile\">\n");
            out.write("<a class=\"tme\"  style=\"cursor:default;\" ><strong>Actions</strong></a><span class=\"hidden menucolon\">: </span><span class=\"submenu hidden\">\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/delete/Sandbox/WebHome\">Delete</a></span>\n");
            out.write("<span class=\"submenuitem\"><a href=\"/xwiki/bin/view/Sandbox/?xpage=rename&amp;step=1\">Rename</a></span>\n");
            out.write("</span></div>\n");
            out.write("<script type=\"text/javascript\">\n");
            out.write("//<![CDATA[\n");
            out.write("  shortcut.add(\"Delete\",function() { location.href=\"/xwiki/bin/delete/Sandbox/WebHome\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("  shortcut.add(\"F2\",function() { location.href=\"/xwiki/bin/view/Sandbox/?xpage=rename&amp;step=1\"; }, { 'type':'keypress', 'propagate':false, 'disable_in_input':true });\n");
            out.write("//]]>\n");
            out.write("</script>\n");
            out.write("  <script type=\"text/javascript\">\n");
            out.write("//<![CDATA[\n");
            out.write("function reloadActionMenu()\n");
            out.write("{\n");
            out.write("  var id = 'menuview';\n");
            out.write("  var surl = '/xwiki/bin/view/Sandbox/?xpage=xpart&vm=menuview.vm';\n");
            out.write("  var myAjax = new Ajax.Updater(\n");
            out.write("    id,\n");
            out.write("    surl,\n");
            out.write("    {\n");
            out.write("      method: 'get',\n");
            out.write("      evalScripts: true,\n");
            out.write("      onComplete: function() {}\n");
            out.write("    });\n");
            out.write("}\n");
            out.write("function watchlist(action)\n");
            out.write("{\n");
            out.write("  var surl = '/xwiki/bin/view/Sandbox/?xpage=watch&do=' + action;\n");
            out.write("  var myAjax = new Ajax.Request(\n");
            out.write("    surl,\n");
            out.write("    {\n");
            out.write("      method: 'get',\n");
            out.write("      onComplete: reloadActionMenu()\n");
            out.write("    });\n");
            out.write("}\n");
            out.write("//]]>\n");
            out.write("</script>\n");
            out.write("              <div class=\"topmenuentry\" onmouseover=\"showsubmenu(this);\" onmouseout=\"hidesubmenu(this);\" id=\"tmWatch\">\n");
            out.write("<a class=\"tme\"  href=\"javascript:watchlist('adddocument')\" ><strong>Watch</strong></a><span class=\"hidden menucolon\">: </span><span class=\"submenu hidden\">\n");
            out.write("              <span class=\"submenuitem\"><a href=\"javascript:watchlist('adddocument')\">Watch this page</a></span>\n");
            out.write("        <span class=\"submenuseparator\">&nbsp;</span>\n");
            out.write("          <span class=\"submenuitem\"><a href=\"javascript:watchlist('addspace')\">Watch whole space</a></span>\n");
            out.write("        <span class=\"submenuseparator\">&nbsp;</span>\n");
            out.write("    <span class=\"submenuitem\"><a href=\"/xwiki/bin/view/XWiki/WatchListManager\">Manage your watchlist</a></span>\n");
            out.write("    </span></div>\n");
            out.write("  </div>\n");
            out.write("</div>\n");
            out.write("\n");
            out.write("</div>\n");
            out.write("<div class=\"contenthideleft\" id=\"contentcontainer\">\n");
            out.write("<div id=\"contentcontainerinner\">\n");
            out.write("<div class=\"leftsidecolumns\">\n");
            out.write("  <div id=\"contentcolumn\"> \n");
            out.write("<div class=\"minwidthb\"></div>\n");
            out.write("<div class=\"main layoutsubsection\">\n");
            out.write("<div id=\"xwikicontent\">\n");
            out.write("<h2 class=\"heading-1\" id=\"HTrainingZone\"><span>Training Zone</span></h2>\n");
            out.write("<span class='edit_section'>&#91;<a style='text-decoration: none;' title='Edit section: Training Zone' href='/xwiki/bin/edit/Sandbox/WebHome?section=1'>edit</a>&#93;</span><p/>\n");
            out.write("You can practice editing here; none of the text is that important.<p/>\n");
            out.write("<h2 class=\"heading-1\" id=\"HHeading109\"><span>Heading 1\t</span></h2>\n");
            out.write("<span class='edit_section'>&#91;<a style='text-decoration: none;' title='Edit section: Heading 1\t' href='/xwiki/bin/edit/Sandbox/WebHome?section=2'>edit</a>&#93;</span>\r\n");
            out.write("<h3 class=\"heading-1-1\" id=\"HHeading209\"><span>Heading 2\t</span></h3>\n");
            out.write("<span class='edit_section'>&#91;<a style='text-decoration: none;' title='Edit section: Heading 2\t' href='/xwiki/bin/edit/Sandbox/WebHome?section=3'>edit</a>&#93;</span>\r\n");
            out.write("<h4 class=\"heading-1-1-1\" id=\"HHeading309\"><span>Heading 3\t</span></h4><p/>\n");
            out.write("<h5 class=\"heading-1-1-1-1\" id=\"HHeading409\"><span>Heading 4\t</span></h5><p/>\n");
            out.write("<h6 class=\"heading-1-1-1-1-1\" id=\"HHeading509\"><span>Heading 5\t</span></h6><p/>\n");
            out.write("<h6 class=\"heading-1-1-1-1-1-1\" id=\"HHeading6\"><span>Heading 6</span></h6><p/>\n");
            out.write("Here is the first paragraph.\r\n");
            out.write("This text continues the same paragraph.<p/>\n");
            out.write("This paragraph is a new one.<p/>\n");
            out.write("a <strong>bold</strong> word\t\r\n");
            out.write("an <em class=\"underline\">underlined</em> word\t\r\n");
            out.write("<em>text in italics</em>\t\r\n");
            out.write("<del>striked text</del><p/>\n");
            out.write("<!--JSON-->\r\n");
            out.write("as;ldfkajsdl;fkasjflaskjfl;asdfkj\r\n");
            out.write("<!--JSON--><p/>\n");
            out.write("<h3 class=\"heading-1-1\" id=\"HLists\"><span>Lists</span></h3>\n");
            out.write("<span class='edit_section'>&#91;<a style='text-decoration: none;' title='Edit section: Lists' href='/xwiki/bin/edit/Sandbox/WebHome?section=4'>edit</a>&#93;</span><p/>\n");
            out.write("<ul class=\"star\">\n");
            out.write("<li>Level 1<ul class=\"star\">\n");
            out.write("<li>Level 2<ul class=\"star\">\n");
            out.write("<li>Level 3</li>\n");
            out.write("</ul></li>\n");
            out.write("<li>Level 2</li>\n");
            out.write("</ul></li>\n");
            out.write("</ul><ol>\n");
            out.write("<li>Item</li>\n");
            out.write("</ol>11.Subitem\r\n");
            out.write("<ol>\n");
            out.write("<li>Item<ul class=\"star\">\n");
            out.write("<li>Subitem</li>\n");
            out.write("</ul></li>\n");
            out.write("</ol><h3 class=\"heading-1-1\" id=\"HLinks\"><span>Links</span></h3>\n");
            out.write("<span class='edit_section'>&#91;<a style='text-decoration: none;' title='Edit section: Links' href='/xwiki/bin/edit/Sandbox/WebHome?section=5'>edit</a>&#93;</span><p/>\n");
            out.write("<ul class=\"star\">\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Sandbox/\">Web Home</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Sandbox/\">home</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/\">Web Home</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/\">home</a></span></li>\n");
            out.write("<li> <span class=\"nobr\"><a href=\"http://www.xwiki.org\">http://www.xwiki.org</a></span></li>\n");
            out.write("<li><span class=\"wikiexternallink\"><a href=\"http://www.xwiki.org\">&#104;ttp://www.xwiki.org</a></span></li>\n");
            out.write("<li><span class=\"wikiexternallink\"><a href=\"http://www.xwiki.org\">To XWiki</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Sandbox/TableTraining\">Table Training</a></span></li>\n");
            out.write("</ul>\n");
            out.write("</div>\n");
            out.write("<div class=\"about\">\n");
            out.write("Version 2.1 last modified by <span class=\"wikilink\"><a href=\"/xwiki/bin/view/XWiki/dieisii\">Dace StrÄlniece</a></span> on 18/07/2008 at 11:32\n");
            out.write("</div>\n");
            out.write("\n");
            out.write("<div id=\"xwikidata\" class=\"layoutsubsection\">\n");
            out.write("<h3 class=\"hidden\">Document data</h3>\n");
            out.write("<div id=\"xwikidatacontents\">\n");
            out.write("  <div id=\"commentscontent\" class=\"xwikiintracontent\">\n");
            out.write("    <div class=\"xwikititlewrapper\" onclick=\"toggleClass($('comments'), 'hidden'); toggleClass($('commentscontent'), 'exp')\"><h3 class=\"xwikiintratitle\">Comments<span class=\"hidden\">:</span> <span class=\"commentsno\"><span>0</span></span></h3></div>    <div id=\"comments\">\n");
            out.write("No comments for this document\n");
            out.write("      <form action=\"/xwiki/bin/commentadd/Sandbox/WebHome\" method=\"post\">\n");
            out.write("        <fieldset class=\"expanded\" id=\"commentform\">\n");
            out.write("        <legend onclick=\"toggleForm(this.form)\">Add Comment<span class=\"expands\">...</span></legend>\n");
            out.write("        <input type=\"hidden\" name=\"xredirect\" value=\"/xwiki/bin/view/Sandbox/\" />\n");
            out.write("        <input type=\"hidden\" name=\"XWiki.XWikiComments_author\" value=\"XWiki.dieisii\"/>\n");
            out.write("        <input type=\"hidden\" name=\"XWiki.XWikiComments_date\" value=\"\"/>\n");
            out.write("        <div><textarea id='XWiki.XWikiComments_comment' rows='5' cols=\"80\" name='XWiki.XWikiComments_comment' style=\"width: 100%;\"></textarea></div>\n");
            out.write("        <div>\n");
            out.write("        <span class=\"buttonwrapper\"><input type=\"submit\" value=\"Add Comment\" class=\"button\"/></span>\n");
            out.write("        <span class=\"buttonwrapper\"><input type=\"reset\" value=\"Cancel\" onclick=\"hideForm(this.form);\" class=\"button\"/></span>\n");
            out.write("        </div>\n");
            out.write("        </fieldset>\n");
            out.write("      </form>\n");
            out.write("    </div>   </div>       <script type=\"text/javascript\">\n");
            out.write("//<![CDATA[\n");
            out.write("if(document.getElementById(\"commentform\")) {\n");
            out.write("  document.getElementById(\"commentform\").className = \"collapsed\";\n");
            out.write("}\n");
            out.write("document.getElementById(\"comments\").className += \" hidden\";\n");
            out.write("//]]>\n");
            out.write("      </script>\n");
            out.write("\n");
            out.write("    <div id=\"attachmentscontent\" class=\"xwikiintracontent\">\n");
            out.write("    <div id=\"attw\">\n");
            out.write("    <div class=\"xwikititlewrapper\" onclick=\"toggleClass($('attachments'), 'hidden'); toggleClass($('attachmentscontent'), 'exp')\"><h3 class=\"xwikiintratitle\">Attachments<span class=\"hidden\">:</span> <span class=\"attachmentsno\">0</span></h3></div>\n");
            out.write("      <div id=\"attachments\">\n");
            out.write("<div>No attachments for this document</div>\n");
            out.write("      <form action=\"/xwiki/bin/upload/Sandbox/WebHome\" enctype=\"multipart/form-data\" method=\"post\">\n");
            out.write("<div>\n");
            out.write("<input type=\"hidden\" name=\"xredirect\" value=\"http://172.16.6.129:8180/xwiki/bin/view/Sandbox/\" />\n");
            out.write("<fieldset class=\"expanded\" id=\"attachform\">\n");
            out.write("        <legend onclick=\"toggleForm(this.form)\">Add an attachment<span class=\"expands\">...</span></legend>\n");
            out.write("     <!--  <div><label id=\"xwikiuploadnamelabel\" for=\"xwikiuploadname\">Choose the target file name:</label></div> -->\n");
            out.write("        <div><input id=\"xwikiuploadname\" type=\"hidden\" name=\"filename\" value=\"\" size=\"40\"/></div>\n");
            out.write("        <div><label id=\"xwikiuploadfilelabel\" for=\"xwikiuploadfile\">Choose file to upload:</label></div>\n");
            out.write("        <div><input id=\"xwikiuploadfile\" type=\"file\" name=\"filepath\" value=\"\" size=\"40\"/></div>\n");
            out.write("        <div>\n");
            out.write("        <span class=\"buttonwrapper\"><input type=\"submit\" value=\"Attach this file\" onclick=\"return updateAttachName(this.form, 'Do you want to replace the filename with')\" class=\"button\"/></span>\n");
            out.write("        <span class=\"buttonwrapper\"><input type=\"reset\" value=\"Cancel\" onclick=\"hideForm(this.form);\" class=\"button\"/></span>\n");
            out.write("        </div>\n");
            out.write("        </fieldset>\n");
            out.write("</div>\n");
            out.write("      </form>\n");
            out.write("      </div>       </div>     </div> <script type=\"text/javascript\">\n");
            out.write("//<![CDATA[\n");
            out.write("document.getElementById(\"attachform\").className = \"collapsed\";\n");
            out.write("document.getElementById(\"attachments\").className = \"hidden\";\n");
            out.write("//]]>\n");
            out.write("</script>\n");
            out.write("\n");
            out.write("</div> </div>  \n");
            out.write("<div class=\"clearfloats\"></div>\n");
            out.write("</div>    </div>\n");
            out.write("  </div><div id=\"rightPanels\" class=\"panels right\">\n");
            out.write("                  <div class=\"panel expanded Search\">\n");
            out.write("<h5 class=\"xwikipaneltitle hidden\" onclick=\"togglePanelVisibility(this.parentNode);\">Search</h5>\n");
            out.write("<div class=\"xwikipanelcontents\">\n");
            out.write("  <form action=\"/xwiki/bin/view/Main/WebSearch\">\n");
            out.write("    <div id=\"globalsearch\">\n");
            out.write("      <input id=\"globalsearchinput\" type=\"text\" name=\"text\" value=\"search...\" size=\"15\" onfocus=\"if (this.value == 'search...') value=''; this.select();\" onblur=\"if (this.value == '') value='search...'; this.blur()\"/>\n");
            out.write("&nbsp;\n");
            out.write("      <input class=\"button\" value=\"Go\" type=\"image\" src=\"/xwiki/skins/albatross/go.png\"/>\n");
            out.write("    </div>\n");
            out.write("  </form>\n");
            out.write("</div>\n");
            out.write("</div>\n");
            out.write("                        <div class=\"panel expanded QuickLinks\">\n");
            out.write("<h5 class=\"xwikipaneltitle\" onclick=\"if(eltHasClass(this.parentNode, 'expanded')) createCookie('XWiki.dieisii_Panels.QuickLinks','collapsed', ''); else eraseCookie('XWiki.dieisii_Panels.QuickLinks'); togglePanelVisibility(this.parentNode);\">Quick Links</h5>\n");
            out.write("<div class=\"xwikipanelcontents\">\n");
            out.write("<ul class=\"star\">\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/\">Home</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/AllDocs\">Index</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/Dashboard\">What's New</a></span> <a href=\"/xwiki/bin/view/Main/RssFeeds\"><img src=\"/xwiki/skins/albatross/icons/black%2Drss%2Dmini3.png\" title=\"RSS Feeds\" alt=\"RSS Feeds\"/></a></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Blog/\">Blog</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/EventCalendar\">Calendar</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Photos/\">Photo Albums</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Sandbox/\">Sandbox</a></span></li>\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/Main/Tags\">Tags</a></span></li>\n");
            out.write("</ul>For Admins:\n");
            out.write("<ul class=\"star\">\n");
            out.write("<li><span class=\"wikilink\"><a href=\"/xwiki/bin/view/XWiki/\">Admin Center</a></span></li>\n");
            out.write("</ul><p style=\"font-size:0.75em;padding-left:8px;\"><a href=\"/xwiki/bin/inline/Panels/QuickLinks\">(Edit this panel)</a></p>\n");
            out.write("</div>\n");
            out.write("</div>\n");
            out.write("                        <div class=\"panel expanded MyRecentModifications\">\n");
            out.write("<h5 class=\"xwikipaneltitle\" onclick=\"if(eltHasClass(this.parentNode, 'expanded')) createCookie('XWiki.dieisii_Panels.MyRecentModifications','collapsed', ''); else eraseCookie('XWiki.dieisii_Panels.MyRecentModifications'); togglePanelVisibility(this.parentNode);\">My Recent Modifications</h5>\n");
            out.write("<div class=\"xwikipanelcontents\">\n");
            out.write("<span class=\"panelitem\"><a href=\"/xwiki/bin/view/Recipes/RecipesBXarImport\">Xar faila importÄÅ¡ana</a></span>\n");
            out.write("<span class=\"pitemseparator\"> | </span>\n");
            out.write("<span class=\"panelitem\"><a href=\"/xwiki/bin/view/Recipes/Recipes9MacroSetup\">Makrosa izveide</a></span>\n");
            out.write("<span class=\"pitemseparator\"> | </span>\n");
            out.write("<span class=\"panelitem\"><a href=\"/xwiki/bin/view/Recipes/Recipes8RecipeClassTemplateSetup\">RecipeClassTemplate sagatavoÅ¡ana</a></span>\n");
            out.write("<span class=\"pitemseparator\"> | </span>\n");
            out.write("<span class=\"panelitem\"><a href=\"/xwiki/bin/view/Recipes/Recipes7RecipeClassEditSheetSetup\">RecipeClassEditSheet sagatavoÅ¡ana</a></span>\n");
            out.write("<span class=\"pitemseparator\"> | </span>\n");
            out.write("<span class=\"panelitem\"><a href=\"/xwiki/bin/view/Recipes/Recipes6RecipeClassSheetSetup\">RecipeClassSheet sagatavoÅ¡ana</a></span>\n");
            out.write("</div>\n");
            out.write("</div>\n");
            out.write("                        <div class=\"panel expanded NewPage\">\n");
            out.write("<h5 class=\"xwikipaneltitle\" onclick=\"if(eltHasClass(this.parentNode, 'expanded')) createCookie('XWiki.dieisii_Panels.NewPage','collapsed', ''); else eraseCookie('XWiki.dieisii_Panels.NewPage'); togglePanelVisibility(this.parentNode);\">Create</h5>\n");
            out.write("<div class=\"xwikipanelcontents\">\n");
            out.write("<form method=\"post\" action=\"/xwiki/bin/view/Sandbox/?xpage=create\">\n");
            out.write("<div class=\"padded centered\">\n");
            out.write("<select name=\"tocreate\" class=\"panelselect\">\n");
            out.write("  <option value=\"page\">New Page&#42;</option>\n");
            out.write("  <option value=\"space\">New Space</option>\n");
            out.write("  <option value=\"post\">New Blog Post</option>\n");
            out.write("</select>\n");
            out.write("</div>\n");
            out.write("<div class=\"padded centered\">\n");
            out.write("<input type=\"hidden\" name=\"template\" value=\"\" />\n");
            out.write("<input type=\"text\" name=\"title\" value=\"Title\" class=\"panelinput\" style=\"margin:auto;\" onfocus=\"if(this.value=='Title') this.value=''\" onblur=\"if(this.value=='') this.value='Title'\"/>\n");
            out.write("</div>\n");
            out.write("<div class=\"padded centered\" style=\"text-align:center;\">\n");
            out.write("<input type=\"submit\" class=\"button\" style=\"margin:auto;\" value=\"Create\"/>\n");
            out.write("</div>\n");
            out.write("<p style=\"font-size:0.75em;padding-left:8px;\">*New pages are created in current space</p>\n");
            out.write("</form>\n");
            out.write("</div>\n");
            out.write("</div>\n");
            out.write("      </div>\n");
            out.write("\n");
            out.write("<div class=\"clearfloats\"></div>\n");
            out.write("  </div></div><div id=\"footerglobal\" class=\"layoutsection\">\n");
            out.write("<div class=\"minwidth\"></div>\n");
            out.write("<hr/>\n");
            out.write("  <div id=\"xwikidocinfo\"><div class=\"minwidth\"></div>Creator: <span class=\"wikilink\"><a href=\"/xwiki/bin/view/XWiki/Admin\">Administrator</a></span> on 2005/01/21 14:46</div>\n");
            out.write("  <div id=\"xwikilicence\">This wiki is licensed under a <a href=\"http://creativecommons.org/licenses/by/1.0/\">Creative Commons</a> license</div>\n");
            out.write("  <div id=\"xwikiplatformversion\">1.4.1.10194</div>\n");
            out.write("<hr/>\n");
            out.write("</div>\n");
            out.write("\n");
            out.write("</div></div></body>\n");
            out.write("</html>");
        } catch (Throwable t) {
            if (!(t instanceof SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0) out.clearBuffer();
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
            }
        } finally {
            if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
